spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234
    url: jdbc:mysql://terraform-20230427110205865900000002.cwa7necgbumd.ap-northeast-2.rds.amazonaws.com:3306/cookcode
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  jwt:
    client-secret: cookcode-dev-secret
  data:
    redis:
      host: cookcode.haneoo.clustercfg.apn2.cache.amazonaws.com
      port: 6379
