spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234
    url: jdbc:mysql://localhost:3306/cookcode
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  jwt:
    client-secret: cookcode-local-secret
  data:
    redis:
      host: localhost
      port: 6379
