name: Deploy Spring boot to test EC2

on:
  push:
    branches:
      - fix/thumbnail

permissions:
  contents: read

env:
  PROJECT_NAME: action_codedeploy

jobs:
  build:
    name: BUILD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Exec Submodule
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build With Gradle
        run: |
          ./gradlew clean build --stacktrace

      - name: Make zip file
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://cookcode-app/test/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Code Deploy to Auto Scaling Group
        run: aws deploy create-deployment --application-name cookcode-dev-deploy --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name dev --s3-location bucket=cookcode-app,bundleType=zip,key=test/$PROJECT_NAME/$GITHUB_SHA.zip
