on:
  push:
    branches:
      - main

name: Deploy Spring boot to Amazon EC2 Auto Scaling Group
env:
  PROJECT_NAME: action_codedeploy

jobs:
  build:
    name: BUILD
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash
